// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_bestClassic1000 = new UnifiedAchievement("BestClassic1000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "best_1000"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQBQ"
#else
            "BestClassic1000"
#endif
            );

        public static UnifiedAchievement BestClassic1000
        {
            get { return s_bestClassic1000; }
        }

        private static readonly UnifiedAchievement s_bestClassic5000 = new UnifiedAchievement("BestClassic5000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "best_5000"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQBg"
#else
            "BestClassic5000"
#endif
            );

        public static UnifiedAchievement BestClassic5000
        {
            get { return s_bestClassic5000; }
        }

        private static readonly UnifiedAchievement s_bestClassic10000 = new UnifiedAchievement("BestClassic10000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "best_10000"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQBw"
#else
            "BestClassic10000"
#endif
            );

        public static UnifiedAchievement BestClassic10000
        {
            get { return s_bestClassic10000; }
        }

        private static readonly UnifiedAchievement s_bestStage10 = new UnifiedAchievement("BestStage10",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_10"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQCA"
#else
            "BestStage10"
#endif
            );

        public static UnifiedAchievement BestStage10
        {
            get { return s_bestStage10; }
        }

        private static readonly UnifiedAchievement s_bestStage30 = new UnifiedAchievement("BestStage30",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_30"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQCQ"
#else
            "BestStage30"
#endif
            );

        public static UnifiedAchievement BestStage30
        {
            get { return s_bestStage30; }
        }

        private static readonly UnifiedAchievement s_bestStage50 = new UnifiedAchievement("BestStage50",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_50"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQCg"
#else
            "BestStage50"
#endif
            );

        public static UnifiedAchievement BestStage50
        {
            get { return s_bestStage50; }
        }

        private static readonly UnifiedAchievement s_bestStage100 = new UnifiedAchievement("BestStage100",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_100"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQCw"
#else
            "BestStage100"
#endif
            );

        public static UnifiedAchievement BestStage100
        {
            get { return s_bestStage100; }
        }

        private static readonly UnifiedAchievement s_bestStage200 = new UnifiedAchievement("BestStage200",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_200"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQDA"
#else
            "BestStage200"
#endif
            );

        public static UnifiedAchievement BestStage200
        {
            get { return s_bestStage200; }
        }

        private static readonly UnifiedAchievement s_bestStage300 = new UnifiedAchievement("BestStage300",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_300"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQDQ"
#else
            "BestStage300"
#endif
            );

        public static UnifiedAchievement BestStage300
        {
            get { return s_bestStage300; }
        }

        private static readonly UnifiedAchievement s_bestStage500 = new UnifiedAchievement("BestStage500",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "stage_500"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQDg"
#else
            "BestStage500"
#endif
            );

        public static UnifiedAchievement BestStage500
        {
            get { return s_bestStage500; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_bestClassic1000,
            s_bestClassic5000,
            s_bestClassic10000,
            s_bestStage10,
            s_bestStage30,
            s_bestStage50,
            s_bestStage100,
            s_bestStage200,
            s_bestStage300,
            s_bestStage500,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "BestClassic1000", s_bestClassic1000 },
            { "BestClassic5000", s_bestClassic5000 },
            { "BestClassic10000", s_bestClassic10000 },
            { "BestStage10", s_bestStage10 },
            { "BestStage30", s_bestStage30 },
            { "BestStage50", s_bestStage50 },
            { "BestStage100", s_bestStage100 },
            { "BestStage200", s_bestStage200 },
            { "BestStage300", s_bestStage300 },
            { "BestStage500", s_bestStage500 },
        };
    }
}
