// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string BestClassic1000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "best_1000";
#elif UNITY_EDITOR
                    return "BestClassic1000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestClassic5000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQBg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "best_5000";
#elif UNITY_EDITOR
                    return "BestClassic5000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestClassic10000
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "best_10000";
#elif UNITY_EDITOR
                    return "BestClassic10000";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage10
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_10";
#elif UNITY_EDITOR
                    return "BestStage10";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage30
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_30";
#elif UNITY_EDITOR
                    return "BestStage30";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage50
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_50";
#elif UNITY_EDITOR
                    return "BestStage50";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_100";
#elif UNITY_EDITOR
                    return "BestStage100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage200
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQDA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_200";
#elif UNITY_EDITOR
                    return "BestStage200";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage300
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQDQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_300";
#elif UNITY_EDITOR
                    return "BestStage300";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestStage500
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "stage_500";
#elif UNITY_EDITOR
                    return "BestStage500";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string BestStage
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQAQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "ave9OkREAIQAQ";
#elif UNITY_EDITOR
                    return "BestStage";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestMulti
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQAg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "ave9OkREAIQAg";
#elif UNITY_EDITOR
                    return "BestMulti";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestClassic
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQAw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "ave9OkREAIQAw";
#elif UNITY_EDITOR
                    return "BestClassic";
#else
                    return string.Empty;
#endif
                }
            }

            public static string BestTimer
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkI-ave9OkREAIQBA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "ave9OkREAIQBA";
#elif UNITY_EDITOR
                    return "BestTimer";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
