// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_bestStage = new UnifiedLeaderboard("BestStage",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "ave9OkREAIQAQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQAQ"
#else
            "BestStage"
#endif
            );

        public static UnifiedLeaderboard BestStage
        {
            get { return s_bestStage; }
        }

        private static readonly UnifiedLeaderboard s_bestMulti = new UnifiedLeaderboard("BestMulti",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "ave9OkREAIQAg"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQAg"
#else
            "BestMulti"
#endif
            );

        public static UnifiedLeaderboard BestMulti
        {
            get { return s_bestMulti; }
        }

        private static readonly UnifiedLeaderboard s_bestClassic = new UnifiedLeaderboard("BestClassic",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "ave9OkREAIQAw"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQAw"
#else
            "BestClassic"
#endif
            );

        public static UnifiedLeaderboard BestClassic
        {
            get { return s_bestClassic; }
        }

        private static readonly UnifiedLeaderboard s_bestTimer = new UnifiedLeaderboard("BestTimer",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "ave9OkREAIQBA"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-ave9OkREAIQBA"
#else
            "BestTimer"
#endif
            );

        public static UnifiedLeaderboard BestTimer
        {
            get { return s_bestTimer; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "BestStage", s_bestStage },
            { "BestMulti", s_bestMulti },
            { "BestClassic", s_bestClassic },
            { "BestTimer", s_bestTimer },
        };
    }
}
